  main = ".open-next/worker.js"
  name = "baitai-fe-test"
  compatibility_date = "2025-12-27"
  compatibility_flags = ["nodejs_compat"]
  [assets]
  directory = ".open-next/assets"
  binding = "ASSETS"